name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  upload:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: src/main/java/org/duoc
          output_file: diagram.svg
          artifact_name: 'DriveQuest Rentals'
          excluded_paths: ".idea,.mvn,.github"

      - name: Upload diagram artifact
        uses: actions/upload-artifact@v4
        with:
          name: diagram
          path: diagram.svg