name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  upload:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: src/main/java/org/duoc
          output_file: diagram.svg
          artifact_name: 'DriveQuest Rentals'
          excluded_paths: ".idea,.mvn,.github"
          should_push: false

      - name: Commit and push diagram
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add diagram.svg
          git commit -m "Update diagram.svg" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Upload diagram artifact
        uses: actions/upload-artifact@v4
        with:
          name: diagram
          path: diagram.svg