name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: src/main/java/org/duoc
          output_file: diagram.svg
          artifact_name: 'DriveQuest Rentals'
          excluded_paths: ".idea,.mvn,.github"

      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "my-diagram"
          path: "downloads"

          